version: '2.1'

networks:
  monitor-net:
    driver: bridge

volumes:
    prometheus_data: {}

services:

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/jenkins_home:/var/jenkins_home
    expose:
      - 8080
      - 50000
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    expose:
      - 9090
    networks:
      - monitor-net

  alertmanager:
    image: prom/alertmanager:v0.20.0
    ports:
      - "9093:9093"
    container_name: alertmanager
    expose:
      - 9093
    networks:
      - monitor-net
